SELECT TOP (1000) [PetID]
      ,[Name]
      ,[Type]
      ,[Breed]
      ,[Age]
      ,[Gender]
      ,[HealthStatus]
      ,[DateAdded]
      ,[Quantity]
      ,[Price]
  FROM [Pet_Shop].[dbo].[Pet_list]
