SELECT TOP (1000) [CategoryID]
      ,[VendorID]
      ,[Name]
      ,[Type]
      ,[Breed]
      ,[Age]
      ,[Quantity]
      ,[Price]
      ,[DateAdded]
      ,[IsActive]
  FROM [Categories].[dbo].[Categories]
